"""
Shared column definitions.

Every table gets an integer surrogate primary key and timezone-aware
audit timestamps generated by the database, not the application. Using
server_default=func.now() means the Postgres clock is authoritative —
timestamps stay consistent even if a future worker process has drift.
"""

from datetime import datetime

from sqlalchemy import DateTime, Enum as SAEnum, func
from sqlalchemy.orm import Mapped, mapped_column

from app.extensions import db
from app.models.enums import enum_values

ENUM_COLUMN_LENGTH = 32


def enum_column(enum_cls, **kwargs):
    """
    Render a Python enum as VARCHAR + CHECK rather than a native
    Postgres ENUM type.

    Native enums need ALTER TYPE to change and Alembic autogenerates
    them poorly. A CHECK constraint gives identical integrity with
    migrations that are ordinary DDL.

    create_constraint=True is NOT optional: SQLAlchemy has defaulted it
    to False since 1.4, so omitting it silently produces a plain VARCHAR
    that accepts any string. That gap is invisible until something
    writes a bad value.
    """
    return mapped_column(
        SAEnum(
            enum_cls,
            native_enum=False,
            create_constraint=True,
            validate_strings=True,
            length=ENUM_COLUMN_LENGTH,
            values_callable=enum_values,
            name=f"ck_{enum_cls.__name__.lower()}",
        ),
        **kwargs,
    )


class TimestampMixin:
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )


class BaseModel(db.Model, TimestampMixin):
    """Abstract: contributes columns but creates no table of its own."""

    __abstract__ = True

    id: Mapped[int] = mapped_column(primary_key=True)

    def __repr__(self) -> str:
        return f"<{type(self).__name__} id={self.id}>"
