"""create clinics, users, patients, appointments, follow_ups

Revision ID: 64de44f235c1
Revises: 
Create Date: 2026-09-07 06:33:48.821127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64de44f235c1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinics',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patients',
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.Enum('male', 'female', 'other', 'undisclosed', name='ck_gender', native_enum=False), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'clinic_id', name='uq_patients_id_clinic')
    )
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.create_index('ix_patients_clinic_name', ['clinic_id', 'full_name'], unique=False)

    op.create_table('users',
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'staff', name='ck_userrole', native_enum=False), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_users_clinic_id', ['clinic_id'], unique=False)

    op.create_table('appointments',
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('appointment_type', sa.Enum('consultation', 'check_up', 'follow_up', 'other', name='ck_appointmenttype', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'confirmed', 'completed', 'cancelled', 'no_show', name='ck_appointmentstatus', native_enum=False), nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id', 'clinic_id'], ['patients.id', 'patients.clinic_id'], name='fk_appointments_patient_clinic', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'clinic_id', name='uq_appointments_id_clinic')
    )
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.create_index('ix_appointments_clinic_scheduled', ['clinic_id', 'scheduled_at'], unique=False)
        batch_op.create_index('ix_appointments_clinic_status', ['clinic_id', 'status'], unique=False)
        batch_op.create_index('ix_appointments_patient_scheduled', ['patient_id', 'scheduled_at'], unique=False)

    op.create_table('follow_ups',
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=True),
    sa.Column('follow_up_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('upcoming', 'completed', name='ck_followupstatus', native_enum=False), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id', 'clinic_id'], ['appointments.id', 'appointments.clinic_id'], name='fk_follow_ups_appointment_clinic', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id', 'clinic_id'], ['patients.id', 'patients.clinic_id'], name='fk_follow_ups_patient_clinic', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('follow_ups', schema=None) as batch_op:
        batch_op.create_index('ix_follow_ups_clinic_status_date', ['clinic_id', 'status', 'follow_up_date'], unique=False)
        batch_op.create_index('ix_follow_ups_patient', ['patient_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follow_ups', schema=None) as batch_op:
        batch_op.drop_index('ix_follow_ups_patient')
        batch_op.drop_index('ix_follow_ups_clinic_status_date')

    op.drop_table('follow_ups')
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_index('ix_appointments_patient_scheduled')
        batch_op.drop_index('ix_appointments_clinic_status')
        batch_op.drop_index('ix_appointments_clinic_scheduled')

    op.drop_table('appointments')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_clinic_id')

    op.drop_table('users')
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_index('ix_patients_clinic_name')

    op.drop_table('patients')
    op.drop_table('clinics')
    # ### end Alembic commands ###
